#!/usr/bin/env python3
from __future__ import annotations

"""Controller Log Visualizer & Diagnostic Analyzer Tool.

Parses CSV logs generated by BipedalRobotController (`bipedal_state_log.csv`) or policy runners.
Generates:
1. Terminal summary report: average control rate (Hz), tracking error statistics, E-STOP events.
2. Standalone interactive HTML report with charts (`bipedal_log_report.html`).

Usage:
    uv run python tools/log_visualizer.py --log-file bipedal_state_log.csv
    uv run python tools/log_visualizer.py --log-file my_experiment.csv --html-out report.html
"""

import argparse
import csv
import json
import sys
import time
from pathlib import Path
from typing import Dict, List, Any
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Controller Log Visualizer & Diagnostic Analyzer."
    )
    parser.add_argument("--log-file", default="bipedal_state_log.csv", help="Path to CSV log file")
    parser.add_argument("--html-out", default="bipedal_log_report.html", help="Path to generated HTML report")
    return parser.parse_args()


def load_log_data(csv_path: Path) -> List[Dict[str, Any]]:
    if not csv_path.exists():
        raise FileNotFoundError(f"Log file not found: {csv_path}")

    rows = []
    with open(csv_path, "r", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            parsed = {}
            for k, v in row.items():
                try:
                    parsed[k] = float(v)
                except ValueError:
                    parsed[k] = v
            rows.append(parsed)
    return rows


def analyze_log(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    if not rows:
        return {"error": "Log file is empty"}

    timestamps = [r.get("timestamp_s", r.get("time_s", r.get("stamp_s", i * 0.01))) for i, r in enumerate(rows)]
    t0 = timestamps[0]
    rel_times = [t - t0 for t in timestamps]
    total_duration = rel_times[-1] if len(rel_times) > 1 else 0.0

    # Compute loop frequency (Hz)
    dt_list = np.diff(rel_times)
    valid_dt = dt_list[dt_list > 0]
    avg_hz = float(1.0 / np.mean(valid_dt)) if len(valid_dt) > 0 else 0.0
    hz_std = float(np.std(1.0 / valid_dt)) if len(valid_dt) > 0 else 0.0

    # Find motor tracking errors
    motor_stats = {}
    for mid in range(1, 13):
        cmd_col = f"m{mid}_cmd_deg"
        meas_col = f"m{mid}_meas_deg"

        if cmd_col in rows[0] and meas_col in rows[0]:
            cmds = np.array([r[cmd_col] for r in rows if cmd_col in r and meas_col in r])
            meas = np.array([r[meas_col] for r in rows if cmd_col in r and meas_col in r])
            errs = np.abs(cmds - meas)
            motor_stats[mid] = {
                "max_err_deg": float(np.max(errs)) if len(errs) > 0 else 0.0,
                "mean_err_deg": float(np.mean(errs)) if len(errs) > 0 else 0.0,
                "std_err_deg": float(np.std(errs)) if len(errs) > 0 else 0.0,
            }

    # E-STOP events
    estop_events = []
    for i, r in enumerate(rows):
        if r.get("estop", 0) in (1, True, "True", "1"):
            estop_events.append({
                "time_s": rel_times[i],
                "reason": r.get("estop_reason", "Unknown"),
            })

    return {
        "num_samples": len(rows),
        "duration_s": total_duration,
        "avg_hz": avg_hz,
        "hz_std": hz_std,
        "motor_stats": motor_stats,
        "estop_events": estop_events,
        "rel_times": rel_times,
    }


def generate_html_report(analysis: Dict[str, Any], rows: List[Dict[str, Any]], out_path: Path) -> None:
    rel_times = analysis["rel_times"]
    time_json = json.dumps([round(t, 3) for t in rel_times])

    # Sample motor 1..4 command vs measured for plot demo
    series_data = []
    for mid in range(1, 13):
        cmd_col = f"m{mid}_cmd_deg"
        meas_col = f"m{mid}_meas_deg"
        if cmd_col in rows[0]:
            cmds = [round(float(r.get(cmd_col, 0.0)), 2) for r in rows]
            meas = [round(float(r.get(meas_col, 0.0)), 2) for r in rows]
            series_data.append({"mid": mid, "cmd": cmds, "meas": meas})

    series_json = json.dumps(series_data)

    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>LeRobot Humanoid - Controller Log Report</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 20px; background: #0f172a; color: #f8fafc; }}
        h1, h2 {{ color: #38bdf8; }}
        .card {{ background: #1e293b; padding: 20px; border-radius: 12px; margin-bottom: 20px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.5); }}
        .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }}
        .metric {{ background: #334155; padding: 15px; border-radius: 8px; text-align: center; }}
        .metric-val {{ font-size: 24px; font-weight: bold; color: #4ade80; }}
        .chart {{ width: 100%; height: 400px; }}
    </style>
</head>
<body>
    <h1>🤖 LeRobot Humanoid Controller Diagnostic Report</h1>
    
    <div class="card">
        <h2>System Performance Summary</h2>
        <div class="grid">
            <div class="metric"><div>Total Duration</div><div class="metric-val">{analysis['duration_s']:.2f} s</div></div>
            <div class="metric"><div>Total Samples</div><div class="metric-val">{analysis['num_samples']}</div></div>
            <div class="metric"><div>Avg Control Rate</div><div class="metric-val">{analysis['avg_hz']:.1f} Hz</div></div>
            <div class="metric"><div>Loop Jitter (StdDev)</div><div class="metric-val">{analysis['hz_std']:.2f} Hz</div></div>
            <div class="metric"><div>E-STOP Events</div><div class="metric-val" style="color: {'#ef4444' if analysis['estop_events'] else '#4ade80'};">{len(analysis['estop_events'])}</div></div>
        </div>
    </div>

    <div class="card">
        <h2>Joint Position Tracking (Command vs Measured)</h2>
        <div id="chart-tracking" class="chart"></div>
    </div>

    <script>
        const times = {time_json};
        const series = {series_json};

        const traces = [];
        series.forEach(s => {{
            traces.push({{
                x: times,
                y: s.cmd,
                mode: 'lines',
                name: `Motor ${{s.mid}} Cmd`,
                line: {{ dash: 'dash' }}
            }});
            traces.push({{
                x: times,
                y: s.meas,
                mode: 'lines',
                name: `Motor ${{s.mid}} Meas`
            }});
        }});

        Plotly.newPlot('chart-tracking', traces, {{
            margin: {{ t: 20, b: 40, l: 50, r: 20 }},
            paper_bgcolor: '#1e293b',
            plot_bgcolor: '#1e293b',
            font: {{ color: '#f8fafc' }},
            xaxis: {{ title: 'Time (s)' }},
            yaxis: {{ title: 'Joint Angle (deg)' }}
        }});
    </script>
</body>
</html>
"""

    with open(out_path, "w") as f:
        f.write(html_content)


def main() -> int:
    args = parse_args()
    csv_path = Path(args.log_file)

    print("=" * 65)
    print("            LeRobot Humanoid - Log Diagnostic Visualizer            ")
    print("=" * 65)

    if not csv_path.exists() or csv_path.stat().st_size == 0:
        print(f"[INFO] Log file '{csv_path}' does not exist or is empty.")
        print("  Generating synthetic example log data for demonstration...")
        # Create a quick synthetic demo CSV file
        with open(csv_path, "w", newline="") as f:
            writer = csv.writer(f)
            header = ["timestamp_s", "estop", "estop_reason"]
            for mid in range(1, 13):
                header.extend([f"m{mid}_cmd_deg", f"m{mid}_meas_deg"])
            writer.writerow(header)

            t = 0.0
            for i in range(100):
                row = [t, 0, ""]
                for mid in range(1, 13):
                    cmd = 10.0 * np.sin(t + mid)
                    meas = cmd + np.random.normal(0, 0.2)
                    row.extend([cmd, meas])
                writer.writerow(row)
                t += 0.01

    rows = load_log_data(csv_path)
    analysis = analyze_log(rows)

    if "error" in analysis or not rows:
        print(f"[ERROR] Could not analyze log file: {analysis.get('error', 'No data rows found')}")
        return 1

    print(f"Log File      : {csv_path.resolve()}")
    print(f"Total Samples : {analysis['num_samples']}")
    print(f"Duration      : {analysis['duration_s']:.2f} seconds")
    print(f"Control Rate  : {analysis['avg_hz']:.1f} Hz (Jitter: ±{analysis['hz_std']:.2f} Hz)")
    print(f"E-STOP Triggers: {len(analysis['estop_events'])}")

    print("-" * 65)
    print("Max Position Tracking Errors (deg):")
    for mid, st in analysis.get("motor_stats", {}).items():
        print(f"  Motor {mid:>2}: Max Err = {st['max_err_deg']:.2f}° | Mean Err = {st['mean_err_deg']:.2f}°")

    html_out = Path(args.html_out)
    generate_html_report(analysis, rows, html_out)
    print("-" * 65)
    print(f"[SUCCESS] Interactive HTML report generated: {html_out.resolve()}")
    print("=" * 65)
    return 0


if __name__ == "__main__":
    sys.exit(main())
